### PR TITLE
feat: refactor css modules to global BEM class

### PR DESCRIPTION
**Pull request by hemengke1997**
This pr add two feature

1. break change: refactor css modules to global class that using BEM convention. Currently, developers must import 'react-simple-toasts/dist/style.css' manually. This gives developers the ability to fully customize css styles
2. add `loadingText` option to customize the loading content
3. replace fixed 300ms exit timeout with `onTransitonEnd`

### CODE REVIEW

**Comment by hemengke1997** [comment]
related to #97

**Comment by hemengke1997** [comment]
> This pr add following features
> 
> 1. break change: refactor css modules to global class that using BEM convention. Currently, developers must import 'react-simple-toasts/dist/style.css' manually. This gives developers the ability to fully customize css styles
> 2. add `loadingText` option to customize the loading content
> 3. replace fixed 300ms exit timeout with `onTransitonEnd`

**Comment by hemengke1997** [comment]
I need some help to fix test cases @almond-bongbong 🤗

**Comment by almond-bongbong** [comment]
I have made some changes to the 'feat/global-css' branch in my fork of the react-simple-toasts repository. These changes include fixing indentation and addressing test issues.

I would like to request that you review and consider merging these changes into the repository. You can view the comparison of the changes here:

[https://github.com/hemengke1997/react-simple-toasts/compare/feat/global-css...almond-bongbong%3Areact-simple-toasts%3Afeat/global-css](https://github.com/hemengke1997/react-simple-toasts/compare/feat/global-css...almond-bongbong%3Areact-simple-toasts%3Afeat/global-css)

The main changes include:
1. 🎨 Fix indent
2. ✅ Fix tests

**Comment by hemengke1997** [comment]
Thank you very much!

**Comment by hemengke1997** [comment]
I found some bug then fix them in this PR, well, maybe I should make new pr, but it's a bit cumbersome to synchronous code from new branch.

**Review by almond-bongbong — APPROVED** [review]

**Pull request merged**
